#!/usr/bin/env bash


GROOVY_DOWNLOAD_URL='https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.5.2.zip'
GROOVY_DOWNLOAD_FILE="/tmp/~`basename "$GROOVY_DOWNLOAD_URL"`"

GROOVY_DIR="/tmp/.groovy"
if [ ! -d "${GROOVY_DIR}" ] ; then
    if [ ! -f "${GROOVY_DOWNLOAD_FILE}" ] ; then
        info "Downloading Groovy"
        curl -sL -o "${GROOVY_DOWNLOAD_FILE}" "${GROOVY_DOWNLOAD_URL}"
    fi
    info "Extracting Groovy"
    mkdir -p "${GROOVY_DIR}"
    unzip -oq "${GROOVY_DOWNLOAD_FILE}" -d "${GROOVY_DIR}"
fi
#find "${GROOVY_DIR}/" -type f -name 'groovy' -perm +111
GROOVYCMD="${GROOVY_DIR}/groovy-2.5.2/bin/groovy"

#echo "JAVACMD=${JAVACMD}"
export JAVACMD
export JAVA_OPTS='--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED'

OCP_PIPELINE_VERSION='0.0.4'
OCP_PIPELINE_DOWNLOAD_URL="https://dl.bintray.com/cvarjao/maven/ca/bc/gov/devops/cd/pipeline/ocp-pipeline/${OCP_PIPELINE_VERSION}/ocp-pipeline-${OCP_PIPELINE_VERSION}.jar"
OCP_PIPELINE_DOWNLOAD_FILE="/tmp/ocp-pipeline-${OCP_PIPELINE_VERSION}.jar"
OCP_PIPELINE_DIR="/tmp/ocp-pipeline-${OCP_PIPELINE_VERSION}"

#OCP_PIPELINE_DIR='/Users/cvarjao/Documents/GitHub/bcdevops/ocp-cd-pipeline/src/main/groovy'

if [ ! -d "${OCP_PIPELINE_DIR}" ] ; then
    if [ ! -f "${OCP_PIPELINE_DOWNLOAD_FILE}" ] ; then
        #echo "Downloading"
        curl -sSf "${OCP_PIPELINE_DOWNLOAD_URL}" -o "${OCP_PIPELINE_DOWNLOAD_FILE}"
    fi
    #echo "Extracting"
    mkdir -p "${OCP_PIPELINE_DIR}"
    unzip -oq "${OCP_PIPELINE_DOWNLOAD_FILE}" -d "${OCP_PIPELINE_DIR}"
fi
