#!/usr/bin/env bash

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
PRG_DIR="`pwd -P`"
cd "$SAVED" >/dev/null

source "${PRG_DIR}/_common"

#find "${OCP_PIPELINE_DIR}" -type f
exec "${GROOVYCMD}" -cp "${OCP_PIPELINE_DIR}" "${OCP_PIPELINE_DIR}/example/deploy.groovy" "$@"